on:
  push:
    branches:
      - main
name: 🚀 Build website on push
jobs:
  Build-website-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
          node-version: '14'
          
    - name: Configure SSH
      env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 700 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
            Host  staging
              HostName $SSH_HOST
              User $SSH_USER
              Port 22
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
          
    - name: 🔨 github server
      working-directory: airbridal
      run: scp staging:/var/www/php81/hirogo-space/airbridal/.env  .env && npm install  && npm run build && mkdir aaaa.txt
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
       server: ${{ secrets.FTP_SERVER }}
       username: ${{ secrets.FTP_USERNAME }}
       password: ${{ secrets.FTP_PASSWORD }}
       local-dir: ./
       server-dir: /php81/hirogo-space-test/
       exclude: | 
        **/.git*
        **/.git*/**
        **/node_modules/**
        *.htaccess
        *.md
        **/vendor/**
        **/tests/**
        **/storage/**
        airbridal/public/assets/plugins/**
        airbridal/public/assets/plugins/**/*
        docker*/**
        pdf*/**
    - name: actual server
      run : ssh staging "cd /var/www/php81/hirogo-space/airbridal/ && php artisan migrate --force"
